version: '2'
services:

  grafana:
    build: grafana
    ports: 
        - 3001:3000
    links:
        - influxdb:influxdb
    environment:
        GF_SERVER_ROOT_URL: https://op.proskive.de/monitoring/grafana/
        GF_SECURITY_ADMIN_USER: admin
        GF_SECURITY_ADMIN_PASSWORD: admin
        GF_SECURITY_SECRET_KEY: grafana
        GF_USERS_ALLOW_SIGN_UP: "true"
        GF_USERS_ALLOW_ORG_CREATE: "true"
        GF_AUTH_ANONYMOUS_ENABLED: "true"
        GF_AUTH_ANONYMOUS_ORG_NAME: grafana
        GF_DASHBOARDS_JSON_ENABLED: "true"
        GF_DASHBOARDS_JSON_PATH: /opt/grafana
        GRAFANA_PLUGINS_ENABLED: "true"
    volumes_from:
        - grafana-data
    networks:
        - tig-stack

  grafana-data:
    image: busybox
    tty: true
    volumes:
        - ./grafana-data:/var/lib/grafana
        - ./grafana-logs:/var/log/grafana
        - ./grafana-plugins:/var/lib/grafana/plugins

  influxdb:
    build: influxdb
    ports:
        - 8083:8083
        - 8086:8086
    environment:
        INFLUX_DATABASE: "telegraf"
        INLFUX_ADMIN_USER: "grafana"
        INFLUX_ADMIN_PASS: "grafana"
    volumes_from:
        - influxdb-data
    networks:
        - tig-stack

  influxdb-data:
    image: busybox
    tty: true
    volumes:
        - ./influx-data:/var/lib/influxdb

  telegraf:
    build: telegraf
    links:
        - influxdb:influxdb
    environment:
        HOST_NAME: "telegraf"
        INFLUXDB_HOST: "influxdb"
        INFLUXDB_PORT: "8086"
        DATABASE: "telegraf"
        HOST_PROC: /host/proc
    tty: true
    volumes:
        - /proc:/host/proc:ro
        - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    networks:
        - tig-stack

networks:
    tig-stack:
